//! Graph contracts, descriptors, and a builder for wiring arbitrary topologies.
//!
//! # Layers
//!
//! - [`descriptor`]: storage-only descriptors (borrowed, owned, and const-buffer).
//! - [`validate`]: descriptor validators (no-alloc port checks; acyclicity with/without `alloc`).
//! - [`builder`] (alloc): ergonomic builder that produces a validated owned descriptor.
//!
//! Runtimes consume the **typed** `Graph` trait; tooling and codegen use descriptors.

use crate::{
    message::{payload::Payload, Message},
    node::{descriptor::NodeDescriptor, StepContext},
    policy::EdgePolicy,
    queue::{descriptor::EdgeDescriptor, SpscQueue},
};

pub mod descriptor;
pub mod validate;

// pub mod builder;

/// Provides indexed access to a graph node.
///
/// This trait is implemented by graph container types (e.g. a generated
/// graph struct) to allow compile-time access to a specific node by index.
///
/// # Type Parameters
/// - `I`: The compile-time index of the node within the graph.
pub trait GraphNodeAccess<const I: usize> {
    /// The concrete node type at index `I`.
    type Node;

    /// Immutable access to the node at index `I`.
    fn node_ref(&self) -> &Self::Node;

    /// Mutable access to the node at index `I`.
    fn node_mut(&mut self) -> &mut Self::Node;
}

// Provides indexed access to a graph edge.
///
/// This trait is implemented by graph container types to allow compile-time
/// access to a specific edge by index.
///
/// # Type Parameters
/// - `E`: The compile-time index of the edge within the graph.
pub trait GraphEdgeAccess<const E: usize> {
    /// The concrete edge type at index `E`.
    type Edge;

    /// Immutable access to the edge at index `E`.
    fn edge_ref(&self) -> &Self::Edge;

    /// Mutable access to the edge at index `E`.
    fn edge_mut(&mut self) -> &mut Self::Edge;
}

/// Defines per-node compile-time types and arity.
///
/// Implemented for each node in the graph by the graph-building macro.  
/// Associates payload types, queue types, and port counts with the node.
///
/// # Type Parameters
/// - `I`:   Compile-time index of the node within the graph.
/// - `IN`:  Number of input ports for the node.
/// - `OUT`: Number of output ports for the node.
pub trait GraphNodeTypes<const I: usize, const IN: usize, const OUT: usize> {
    /// Payload type for messages consumed by the node.
    type InP: Payload;

    /// Payload type for messages produced by the node.
    type OutP: Payload;

    /// Queue type used for input ports.
    type InQ: SpscQueue<Item = Message<Self::InP>>;

    /// Queue type used for output ports.
    type OutQ: SpscQueue<Item = Message<Self::OutP>>;
}

/// Builder for per-node execution contexts.
///
/// This trait is implemented by the graph-building macro. It allows the runtime
/// to create a [`StepContext`] for a given node using compile-time wiring of its
/// ports, queues, and policies.
///
/// # Type Parameters
/// - `I`:   Compile-time index of the node within the graph.
/// - `IN`:  Number of input ports for the node.
/// - `OUT`: Number of output ports for the node.
pub trait GraphNodeContextBuilder<const I: usize, const IN: usize, const OUT: usize>:
    GraphNodeTypes<I, IN, OUT>
{
    /// Construct a [`StepContext`] for node `I`.
    ///
    /// # Parameters
    /// - `clock`:     Reference to the runtime clock abstraction.
    /// - `telemetry`: Mutable reference to the telemetry collector.
    ///
    /// # Returns
    /// A fully wired [`StepContext`] for the node, ready for execution.
    fn make_step_context<C, T>(
        &mut self,
        clock: &C,
        telemetry: &mut T,
    ) -> StepContext<
        IN,
        OUT,
        <Self as GraphNodeTypes<I, IN, OUT>>::InP,
        <Self as GraphNodeTypes<I, IN, OUT>>::OutP,
        <Self as GraphNodeTypes<I, IN, OUT>>::InQ,
        <Self as GraphNodeTypes<I, IN, OUT>>::OutQ,
        C,
        T,
    >
    where
        EdgePolicy: Copy;
}

/// Unified runtime-facing graph API.
///
/// Implemented by graph container types generated by the builder macro.
/// Provides access to node and edge descriptors, and convenience helpers for
/// accessing nodes, edges, and building step contexts.
///
/// # Type Parameters
/// - `NODE_COUNT`: Total number of nodes in the graph.
/// - `EDGE_COUNT`: Total number of edges in the graph.
pub trait GraphApi<const NODE_COUNT: usize, const EDGE_COUNT: usize> {
    /// Return static descriptors for all nodes in the graph.
    fn get_node_descriptors(&self) -> [NodeDescriptor; NODE_COUNT];

    /// Return static descriptors for all edges in the graph.
    fn get_edge_descriptors(&self) -> [EdgeDescriptor; EDGE_COUNT];

    /// Immutable access to node `I`.
    #[inline]
    fn get_node_ref<const I: usize>(&self) -> &<Self as GraphNodeAccess<I>>::Node
    where
        Self: GraphNodeAccess<I>,
    {
        <Self as GraphNodeAccess<I>>::node_ref(self)
    }

    /// Mutable access to node `I`.
    #[inline]
    fn get_node_mut<const I: usize>(&mut self) -> &mut <Self as GraphNodeAccess<I>>::Node
    where
        Self: GraphNodeAccess<I>,
    {
        <Self as GraphNodeAccess<I>>::node_mut(self)
    }

    /// Immutable access to edge `E`.
    #[inline]
    fn get_edge_ref<const E: usize>(&self) -> &<Self as GraphEdgeAccess<E>>::Edge
    where
        Self: GraphEdgeAccess<E>,
    {
        <Self as GraphEdgeAccess<E>>::edge_ref(self)
    }

    /// Mutable access to edge `E`.
    #[inline]
    fn get_edge_mut<const E: usize>(&mut self) -> &mut <Self as GraphEdgeAccess<E>>::Edge
    where
        Self: GraphEdgeAccess<E>,
    {
        <Self as GraphEdgeAccess<E>>::edge_mut(self)
    }

    /// Build a [`StepContext`] for node `I` using its compile-time wiring.
    ///
    /// Delegates to the node’s [`GraphNodeContextBuilder`] implementation.
    #[inline]
    fn make_step_context_for_node<const I: usize, const IN: usize, const OUT: usize, C, T>(
        &mut self,
        clock: &C,
        telemetry: &mut T,
    ) -> StepContext<
        IN,
        OUT,
        <Self as GraphNodeTypes<I, IN, OUT>>::InP,
        <Self as GraphNodeTypes<I, IN, OUT>>::OutP,
        <Self as GraphNodeTypes<I, IN, OUT>>::InQ,
        <Self as GraphNodeTypes<I, IN, OUT>>::OutQ,
        C,
        T,
    >
    where
        Self: GraphNodeContextBuilder<I, IN, OUT> + GraphNodeTypes<I, IN, OUT>,
        EdgePolicy: Copy,
    {
        <Self as GraphNodeContextBuilder<I, IN, OUT>>::make_step_context(self, clock, telemetry)
    }
}
