name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - release/*

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        profile: [no-default-features, alloc, std, spsc_raw]
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable

      - name: Cache cargo registry
        uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ matrix.profile }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Rustfmt check
        run: cargo fmt --all -- --check

      - name: Build, test, clippy & doc (no-default-features)
        if: matrix.profile == 'no-default-features'
        run: |
          cargo build --all --no-default-features --all-targets --verbose
          cargo test --all --no-default-features --all-targets --verbose
          cargo clippy --all --no-default-features -- -D warnings
          RUSTDOCFLAGS="-D warnings" cargo doc --workspace --no-deps --no-default-features

      - name: Build, test, clippy & doc (alloc)
        if: matrix.profile == 'alloc'
        run: |
          cargo build --all --features alloc --all-targets --verbose
          cargo test  --all --features alloc --all-targets --verbose
          cargo clippy --all --features alloc -- -D warnings
          RUSTDOCFLAGS="-D warnings" cargo doc --workspace --no-deps --features alloc

      - name: Build, test, clippy & doc (std)
        if: matrix.profile == 'std'
        run: |
          cargo build --all --features std --all-targets --verbose
          cargo test  --all --features std --all-targets --verbose
          cargo clippy --all --features std -- -D warnings
          RUSTDOCFLAGS="-D warnings" cargo doc --workspace --no-deps --features std

      - name: Build, test, clippy & doc (spsc_raw)
        if: matrix.profile == 'spsc_raw'
        run: |
          cargo build --all --features spsc_raw --all-targets --verbose
          cargo test  --all --features spsc_raw --all-targets --verbose
          cargo clippy --all --features spsc_raw -- -D warnings
          RUSTDOCFLAGS="-D warnings" cargo doc --workspace --no-deps --features spsc_raw

  deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: EmbarkStudios/cargo-deny-action@v2
